#!/bin/sh
#
# Enlaces y Comunicaciones del Sureste, S.A. de C.V.
# Derechos Reservados 2002-2008
#
# Descripcion: Depura carpeta de respaldos de los logs de SQUID
# Version: 1.0
# Actualizacion: 23 de Agosto de 2008
#

DEST_DIR=/home/robot
RESP_DIR=/opt/respaldos_bitacoras_EE
LOG_FILE=/var/log/delete_log_backups

TODAY=`date "+%Y%m%d"`
DATE_TO_DELETE=`date -d '-10 days' "+%d-%b-%Y"`
echo $DATE_TO_DELETE
echo $TODAY

#cd $RESP_DIR
#echo `date` >> $LOG_FILE
#rm -v -fR $DATE_TO_DELETE  >> $LOG_FILE

