#!/bin/sh
# Shell script to monitor or watch the disk space
# It will send an email to $ADMIN, if the used disk percentage
# is >= 90%
# -------------------------------------------------------------------------
# Copyright (c) 2005 nixCraft project <http://cyberciti.biz/fb/>
# This script is licensed under GNU GPL version 2.0 or above
# -------------------------------------------------------------------------
# This script is part of nixCraft shell script collection (NSSC)
# Visit http://bash.cyberciti.biz/ for more information.
# ----------------------------------------------------------------------
# Linux shell script to watch disk space (should work on other UNIX oses )
# SEE URL: http://www.cyberciti.biz/tips/shell-script-to-watch-the-disk-space.html
# set admin email so that you can get email
ADMIN="alan@megamedia.com.mx, programacion@megamedia.com.mx, netstaff@megamedia.com.mx"
# set alert level 90% is default
ALERT=90
df -H -t ext3 | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{ print $4 " " $5 " " $1}' | while read output;
do
  #echo $output
  avail=$(echo $output | awk '{ print $1}' )
  usep=$(echo $output | awk '{ print $2}' | cut -d'%' -f1  )
  partition=$(echo $output | awk '{ print $3 }' )
  if [ $usep -ge $ALERT ]; then
    echo "Running out of space, only $avail available in \"$partition ($usep%)\" on $(hostname) as on $(date)" |
     mail -s "Alert: Almost out of disk space $usep% only $avail available" $ADMIN -- -F "Monitor Dinamo"
  fi
done

