#!/bin/sh
#
# All Rights Reserved 2008 -- Red y Comunicacion, Grupo Megamedia
#
# Desc: Sincroniza desde vancouver los directorios especificados en el
#       archivo /usr/local/bin/sync_from_illinois_dirs
# Date: Agosto 06, 2010
#

LOG=/var/log/RSSCopy.log
DIRS=/usr/local/bin/RSSCopy_dirs
LOCK=/var/run/sync.RSS.lock

echo "`date` - Comienza la generacion de RSS" >> $LOG

/usr/bin/php /var/www/html/v7/cron/rss.php > $LOG


if [ -f "$LOCK" ] ; then

echo "`date` - La Sincronizacion anterior no ha finalizado" >> $LOG
exit

else

`touch $LOCK`
date >> $LOCK

echo ">>>> `date` - Inicia proceso de sincronizacion $i <<<<" >> $LOG

for i in `cat $DIRS`
  do

        echo "Content-type: text/html"
        echo ""
        echo "<html><head><title>Sincroniza la carpeta $i</title></head><body>"

        echo "`date` - Realizando Sincronizacion de $i" >> $LOG

        # La sincronizacion se realiza con RSYNC
	rsync -vauz --remove-source-files --log-file=$LOG /var/www/html/v7/$i/ root@murdoch:/var/www/html/edicion/rss/


        echo "`date` - Sincronizacion de $i Finalizada" >> $LOG
  done

echo "---- `date` - Proceso de sincronizacion finalizado ----" >> $LOG

`rm -f $LOCK`

fi

echo "`date` - Proceso COMPLETADO" >> $LOG

exit
