#!/bin/sh
#
#  Sync EE files to replica Servers
#  By alan@megamedia.com.mx
#  Updated: 18 Oct 2012
#

REMOTE_SERVER="dogwood.sureste.com bonsai.sureste.com holly.sureste.com"
WEBSITE_DIR=/var/www/yucatan.com.mx
DEST_DIR=/var/www
LOG=/var/log/sync_to_replicas.log
LOCK=/var/lock/sync_to_replicas.lock
RSYNC_EXCLUDES=/etc/rsync/rsync-exclusions.conf 
NOTIFY_EXCLUDES=".tmp"

inotifywait -r -m -e close_write --format '%w%f' $WEBSITE_DIR | grep -v '$NOTIFY_EXCLUDES' |\
while read file
do
	if [ -f $file ] ; then
        	echo "`date "+%F %X"` - $file" >> $LOG
		for server in $REMOTE_SERVER
		do
			rsync -aquzL --exclude-from=$RSYNC_EXCLUDES $file $server:$file >> $LOG 2>&1
		done
	else
        	echo "`date "+%F %X"` - No existe $file" >> $LOG
	fi
done
